---
# Tasks for python testing
- name: Ensure python packages are present
  package:
    name: "{{ item }}"
    state: "present"
  loop: "{{ python_packages }}"

- name: Ensure testing pips are present
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ pips }}"
