---
# Tasks for ruby test environment
- name: "Ensure ruby"
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ ruby_packages }}"

- name: Ensure gems
  become: true
  become_user: jenkins
  gem:
    name: "{{ item.name }}"
    include_dependencies: true
    state: present
    version: "{{ item.version }}"
    user_install: true
  loop: "{{ gems }}"
